---
geometry_msgs/PoseStamped[] victimsToGo
geometry_msgs/PoseStamped[] victimsVisited
geometry_msgs/PoseStamped[] holes
geometry_msgs/PoseStamped[] obstacles
geometry_msgs/PoseStamped[] hazmats
geometry_msgs/PoseStamped[] landoltcs
geometry_msgs/PoseStamped[] qrs
geometry_msgs/PoseStamped[] thermals
geometry_msgs/PoseStamped[] victimImages
geometry_msgs/PoseStamped[] motions
geometry_msgs/PoseStamped[] sounds
geometry_msgs/PoseStamped[] co2s
geometry_msgs/PoseStamped[] dataMatrices
