---
visualization_msgs/MarkerArray victimsToGo
visualization_msgs/MarkerArray victimsVisited
visualization_msgs/MarkerArray holes
visualization_msgs/MarkerArray stereoHoles
visualization_msgs/MarkerArray hazmats
visualization_msgs/MarkerArray qrs
visualization_msgs/MarkerArray tpas
